import path from 'path';
import fs from 'fs-extra';
import { StackConfig } from '../types';

export async function generateCommon(config: StackConfig, targetDir: string) {
    // Generate root package.json
    const rootPackageJson = {
        name: config.projectName,
        version: '0.1.0',
        private: true,
        engines: {
            node: '>=20.0.0'
        },
        workspaces: ['frontend', 'backend'],
        scripts: {
            setup: 'cp .env.example .env || copy .env.example .env',
            dev: 'npx concurrently "npm run dev --workspace=frontend" "npm run dev --workspace=backend"',
            'dev:frontend': 'npm run dev --workspace=frontend',
            'dev:backend': 'npm run dev --workspace=backend',
            build: 'npm run build --workspaces',
            test: 'npm run test --workspaces',
        },
        devDependencies: {
            concurrently: '^8.2.2',
        },
        author: 'Generated by ForgeStack OS',
        license: 'MIT',
    };

    await fs.writeJSON(path.join(targetDir, 'package.json'), rootPackageJson, { spaces: 2 });

    // Generate .gitignore
    const gitignore = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Production
build/
dist/
.next/
out/

# Environment
.env
.env.local
.env.*.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo

# Database
*.db
*.sqlite
prisma/migrations/

# Docker
docker-compose.override.yml
`;

    await fs.writeFile(path.join(targetDir, '.gitignore'), gitignore);

    // Generate README.md
    const readme = generateReadme(config);
    await fs.writeFile(path.join(targetDir, 'README.md'), readme);

    // Generate .env.example
    const envExample = generateEnvExample(config);
    await fs.writeFile(path.join(targetDir, '.env.example'), envExample);
}

function generateReadme(config: StackConfig): string {
    return `# ${config.projectName}

Generated by **ForgeStack OS** - One platform. Any stack. Production-ready.

## Stack

- **Frontend:** ${config.frontend}
- **Backend:** ${config.backend}
- **Auth:** ${config.auth}
- **Database:** ${config.database}
- **API Style:** ${config.apiStyle}
- **Docker:** ${config.docker ? 'Yes' : 'No'}
- **Multi-Tenant:** ${config.multiTenant ? 'Yes' : 'No'}

## Getting Started

### Prerequisites

- Node.js 18+ (or Bun if using Bun backend)
${config.backend === 'go-fiber' ? '- Go 1.21+' : ''}
${config.docker ? '- Docker and Docker Compose' : ''}
${config.database === 'postgresql' ? '- PostgreSQL (or use Docker)' : ''}
${config.database === 'mongodb' ? '- MongoDB (or use Docker)' : ''}

### Installation

\`\`\`bash
# Install dependencies
npm install

# Copy environment variables
cp .env.example .env

# Update .env with your configuration
\`\`\`

### Database Setup

${getDatabaseSetupInstructions(config)}

### Development

\`\`\`bash
# Run both frontend and backend
npm run dev

# Or run separately
npm run dev:frontend
npm run dev:backend
\`\`\`

${config.docker ? `### Docker

\`\`\`bash
# Start all services
docker-compose up

# Start in detached mode
docker-compose up -d

# Stop services
docker-compose down
\`\`\`
` : ''}

## Project Structure

\`\`\`
${config.projectName}/
├── frontend/          # ${config.frontend} application
├── backend/           # ${config.backend} server
${config.docker ? '├── docker/            # Docker configuration' : ''}
├── .env.example       # Environment variables template
└── README.md          # This file
\`\`\`

## Authentication

${getAuthInstructions(config)}

${config.multiTenant ? `## Multi-Tenancy

This application is configured with multi-tenancy support. Each request is automatically scoped to a tenant based on:

${getTenantScopingInfo(config)}

All database queries include tenant isolation to ensure data security.
` : ''}

## Built With

- [ForgeStack OS](https://github.com/halloffame12/forgestack-os) - The meta-platform that generated this project
- Created by [Sumit Chauhan](https://github.com/halloffame12)

## License

MIT
`;
}

function getDatabaseSetupInstructions(config: StackConfig): string {
    switch (config.database) {
        case 'postgresql':
            return `\`\`\`bash
# Using Docker
docker-compose up -d postgres

# Or install PostgreSQL locally and create a database
createdb ${config.projectName}

# Run migrations
cd backend
npx prisma migrate dev
\`\`\``;

        case 'mongodb':
            return `\`\`\`bash
# Using Docker
docker-compose up -d mongodb

# Or install MongoDB locally
# No migrations needed - Mongoose handles schema
\`\`\``;

        case 'mysql':
            return `\`\`\`bash
# Using Docker
docker-compose up -d mysql

# Or install MySQL locally and create a database
mysql -u root -p -e "CREATE DATABASE ${config.projectName};"

# Run migrations
cd backend
npx prisma migrate dev
\`\`\``;

        case 'sqlite':
            return `\`\`\`bash
# SQLite is file-based, no setup needed
# Database file will be created automatically
cd backend
npx prisma migrate dev
\`\`\``;

        case 'supabase-db':
            return `\`\`\`bash
# Create a Supabase project at https://supabase.com
# Copy your connection string to .env
# Run migrations through Supabase dashboard or CLI
\`\`\``;

        default:
            return 'See backend/README.md for database setup instructions.';
    }
}

function getAuthInstructions(config: StackConfig): string {
    switch (config.auth) {
        case 'jwt':
            return `This project uses built-in JWT authentication. Users can register and login through the API endpoints:

- \`POST /api/auth/register\` - Create a new account
- \`POST /api/auth/login\` - Login and receive JWT token
- Include the token in requests: \`Authorization: Bearer <token>\``;

        case 'clerk':
            return `This project uses Clerk for authentication. 

1. Create a Clerk account at https://clerk.com
2. Create a new application
3. Copy your API keys to \`.env\`
4. Configure allowed redirect URLs in Clerk dashboard`;

        case 'supabase':
            return `This project uses Supabase Auth.

1. Create a Supabase project at https://supabase.com
2. Copy your project URL and anon key to \`.env\`
3. Configure auth providers in Supabase dashboard`;

        case 'authjs':
            return `This project uses Auth.js (NextAuth).

1. Configure providers in \`backend/src/auth/config.ts\`
2. Add provider credentials to \`.env\`
3. See https://authjs.dev for provider setup guides`;

        case 'firebase':
            return `This project uses Firebase Auth.

1. Create a Firebase project at https://firebase.google.com
2. Enable authentication methods
3. Copy your config to \`.env\``;

        default:
            return 'See documentation for authentication setup.';
    }
}

function getTenantScopingInfo(config: StackConfig): string {
    switch (config.auth) {
        case 'clerk':
            return '- Clerk organization ID is used as tenant ID\n- Organization membership determines access';
        case 'supabase':
            return '- Supabase user metadata contains tenant_id\n- Row Level Security (RLS) policies enforce isolation';
        case 'jwt':
            return '- JWT token contains tenant_id claim\n- Middleware extracts and validates tenant context';
        default:
            return '- Authentication provider includes tenant information\n- Middleware enforces tenant isolation';
    }
}

function generateEnvExample(config: StackConfig): string {
    let env = `# Database
DATABASE_URL="${getDatabaseUrl(config)}"

# Server
PORT=3000
NODE_ENV=development

`;

    // Auth-specific variables
    switch (config.auth) {
        case 'jwt':
            env += `# JWT Authentication
JWT_SECRET=your-super-secret-jwt-key-change-this
JWT_EXPIRES_IN=7d
`;
            break;

        case 'clerk':
            env += `# Clerk Authentication
CLERK_PUBLISHABLE_KEY=pk_test_xxxxx
CLERK_SECRET_KEY=sk_test_xxxxx
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_xxxxx
`;
            break;

        case 'supabase':
            env += `# Supabase
SUPABASE_URL=https://xxxxx.supabase.co
SUPABASE_ANON_KEY=xxxxx
SUPABASE_SERVICE_ROLE_KEY=xxxxx
NEXT_PUBLIC_SUPABASE_URL=https://xxxxx.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=xxxxx
`;
            break;

        case 'authjs':
            env += `# Auth.js
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=your-secret-key-change-this
GOOGLE_CLIENT_ID=xxxxx
GOOGLE_CLIENT_SECRET=xxxxx
`;
            break;

        case 'firebase':
            env += `# Firebase
FIREBASE_API_KEY=xxxxx
FIREBASE_AUTH_DOMAIN=xxxxx.firebaseapp.com
FIREBASE_PROJECT_ID=xxxxx
NEXT_PUBLIC_FIREBASE_API_KEY=xxxxx
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=xxxxx.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=xxxxx
`;
            break;
    }

    // Frontend URL
    env += `\n# Frontend
FRONTEND_URL=http://localhost:5173
`;

    return env;
}

function getDatabaseUrl(config: StackConfig): string {
    switch (config.database) {
        case 'postgresql':
            return 'postgresql://user:password@localhost:5432/dbname';
        case 'mongodb':
            return 'mongodb://localhost:27017/dbname';
        case 'mysql':
            return 'mysql://user:password@localhost:3306/dbname';
        case 'sqlite':
            return 'file:./dev.db';
        case 'supabase-db':
            return 'postgresql://postgres:password@db.xxxxx.supabase.co:5432/postgres';
        default:
            return 'your-database-connection-string';
    }
}
