export default function HomePage() {
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      <div className="container mx-auto px-4 py-16">
        <h1 className="text-5xl font-bold mb-4">test-app-nextjs</h1>
        <p className="text-xl text-gray-400 mb-8">
          Generated by ForgeStack OS
        </p>
        <div className="space-x-4">
          <a
            href="/login"
            className="inline-block bg-blue-600 hover:bg-blue-700 px-6 py-3 rounded font-semibold"
          >
            Get Started
          </a>
        </div>
      </div>
    </div>
  )
}
